export const fallbackBlogs = [
  {
    id: 'fallback-17-second-rule',
    title: 'The 17-Second Rule: A Cheesecake Lesson at Delhi Airport',
    slug: '17-second-rule',
    category: 'Manifestation',
    image_url: '/images/manifestation-coaching.jpg',
    excerpt:
      '17 seconds of pure, joyful focus at a Delhi airport turned cheesecake disappointment into a fresh slice—here is the full story and how to practice the 17-second rule yourself.',
    created_at: '2024-12-15T00:00:00.000Z',
    published: true,
    content: [
      'Story — Cheesecake at Delhi airport',
      'Last July at Delhi airport, my son was craving a slice of cheesecake. Starbucks had just sold out, and disappointment hit fast.',
      'Instead of lingering there, I reminded him of the 17-second rule: hold a pure, positive thought for 17 seconds and you start activating its vibration. I was quietly hoping we might find a slice when we landed a couple of hours later.',
      'He closed his eyes, set a 17-second timer on his watch, and visualized a perfect slice—blueberry jelly on top, creamy filling, and a sweet graham crust. He felt the anticipation as if it were already in his hands.',
      'When he opened his eyes, he smiled and said it felt so real. We let it go, grabbed iced coffee, and found a corner table.',
      'Within minutes, the waiter returned: their outside baker had arrived early with a fresh batch of pastries—cheesecake included. The delight in my son’s eyes said everything.',
      'What is the 17-second rule?',
      'A concept popularized by Abraham Hicks: 17 seconds of undiluted focus sparks the vibration of your thought; 34, 51, and 68 seconds build momentum and make it feel closer and stronger.',
      'Science & spirit: your reticular activating system (RAS) highlights what you focus on, priming you to notice matching opportunities. Energetically, your field acts like a magnet, inviting aligned people and moments.',
      'How to practice — four quick steps',
      '1) Choose your thought: Pick one clear, uplifting idea (vision, desire, or feeling like joy/love/abundance).',
      '2) Focus for 17 seconds: Close your eyes, hold it with laser focus, feel it as if it is happening now.',
      '3) Build momentum: If it feels good, ride it to 34, 51, or 68 seconds—each checkpoint strengthens the signal.',
      '4) Release and receive: Let it go. Do not keep checking. Stay light and open to synchronicities.',
      'Start small: try it on a calm meeting, a smooth commute, or a helpful colleague. Notice how a short burst of focused attention can reset your energy and invite matching experiences.'
    ],
  },
  {
    id: 'fallback-cord-cutting-only-way',
    title: 'Is Cord Cutting the ONLY Way?',
    slug: 'is-cord-cutting-the-only-way',
    category: 'Energy Healing',
    image_url: '/images/tarot-guidance.jpg',
    excerpt:
      'Etheric cords link us to people, places, and lessons. Before you rush to “cut,” understand how cords behave, why lessons repeat, and how love + forgiveness can dissolve what hurts.',
    created_at: '2024-12-20T00:00:00.000Z',
    published: true,
    content: [
      'They say relationships are made in heaven, bound before birth. Yet breakups and broken friendships make us ask: where does that soul connection go when love turns to resentment?',
      'Let spirituality answer: we are linked by Etheric Cords—subtle energy structures connecting people, places, animals, and objects through our chakras. The quality of emotion running through these cords shapes how we relate physically, mentally, and emotionally.',
      'Etheric cords are not static. A bright, heart-centered bond can dim or shift as a relationship changes. Cords can link through heart, eye, and other chakras, moving with the dynamics of connection.',
      'Detachment and “cutting the cord” is often advised when breakups or heartaches bring discomfort. Cord cutting aims to release negative emotions, patterns, and influences, helping you reclaim energy and freedom.',
      'But is cord cutting the only way? Consider this story from a seeker who cut cords with her ex, felt instant relief, then found the relationship reignite—only to crash harder. The cut did not end the lesson; it seemed to amplify it.',
      'Why be cautious with cord cutting? Energetic cords behave like roots—cutting can stimulate regrowth, sometimes stronger. The issues you hoped to dissolve may reactivate if the underlying lesson remains unlearned.',
      'Energy and vibration: everything carries a frequency. Relationships make us aware of these vibrations. Our first cord—the umbilical cord—shows that even when a cord is severed, connection persists. Life-force exchange and lessons remain.',
      'Soul contracts and lessons: many spiritual traditions say souls agree to meet and grow together. Earth is a school. If you cut a cord before integrating the lesson (jealousy, fear, ego, attachment), the pattern often returns through new people or situations until you evolve past it.',
      'A gentler path: instead of cutting, consider cleansing and dissolving with awareness.',
      '1) Pause and observe: What lesson or pattern is repeating? Where in the body do you feel it?',
      '2) Forgive and soften: Send forgiveness and compassion toward yourself and the other. This lowers resistance and reduces charge in the cord.',
      '3) Clear the field: Use breathwork, salt baths, nature walks, or sound to lighten your energy before any deeper work.',
      '4) Dialogue with the cord: In meditation, see the cord as a root. Ask what it is teaching you. Let light dissolve stagnant sections instead of hacking it away.',
      '5) Seal and bless: If a connection truly needs ending, imagine the cord gently dissolving into light, seal your aura with gold or violet light, and bless all involved.',
      'Remember: cords tend to regrow if the lesson is unfinished. By integrating the lesson through love, forgiveness, and self-improvement, relationships naturally shift—either becoming harmonious or fading without force.',
    ],
  },
  {
    id: 'fallback-slow-down-reset',
    title: '10 Warning Signs Your Life Is Asking You to Slow Down and Reset',
    slug: '10-warning-signs-to-slow-down',
    category: 'Mindfulness',
    image_url: '/images/hero-image.jpg',
    excerpt:
      'Life whispers before it screams. Notice these 10 everyday signals—from clumsy mishaps to lost joy—that ask you to pause, realign, and reset.',
    created_at: '2024-12-22T00:00:00.000Z',
    published: true,
    content: [
      'Life has a way of whispering before it screams. The body, mind, and universe send subtle signals when you are out of balance—but busyness and distraction can drown them out.',
      'Here are ten everyday warning signs inviting you to slow down, realign, and reset:',
      '1) A streak of clumsy accidents: breaking glasses, bumping your head, stubbing your toe on the same corner. These “silly” mishaps are your body saying: slow down, be here now.',
      '2) A scattered mind: you keep running—scrolling, overbooking, filling space so you never sit with yourself. This is a functional freeze: nervous system in overdrive, spirit on pause.',
      '3) Irritation and anxiety “for no reason”: tiny things trigger you; worry hums without a clear source. Your inner alarm is asking: pay attention—something is off.',
      '4) Frequent illnesses or chronic aches: headaches, recurring flus, fatigue that sleep does not fix. An unsettled inner world echoes through the body.',
      '5) Losing joy: what once made you laugh or glow now feels dull. Disappearing joy is a clear sign you have drifted from your aligned path.',
      '6) Repeating angel numbers like 666 or 606: not bad luck, but a cosmic sticky note to stop, recheck, and reassess your thoughts and actions in that moment.',
      '7) Ignoring your intuition: you know what feels right, yet you dismiss it from fear or pressure. Silencing your inner compass leaves you unmoored.',
      '8) Clutter everywhere: home, desk, digital life all feel messy. Clutter is stuck energy; outer chaos mirrors inner chaos.',
      '9) Social autopilot: you keep saying yes while feeling emptier after every interaction. Your energy budget is overdrawn; boundaries need a reset.',
      '10) Sleep that does not restore: you sleep but wake up tired, or you cannot settle. Your nervous system is asking for gentler rhythms and true rest.',
      'Bottom line: these signs are not flaws; they are gentle nudges to pause, recenter, and reconnect. When you heed them, life begins to flow with you instead of against you.',
    ],
  },
  {
    id: 'fallback-movies-that-teach',
    title: 'Movies That Feel Like Warm Hugs for the Soul',
    slug: 'movies-that-feel-like-warm-hugs',
    category: 'Inspiration',
    image_url: '/images/about-me.jpg',
    excerpt:
      'Films can be sacred pauses that whisper wisdom. Here are heartfelt picks—from Anand to Dear Zindagi—that nudge us toward joy, courage, and spiritual insight.',
    created_at: '2024-12-24T00:00:00.000Z',
    published: true,
    content: [
      'Sometimes life whispers its lessons, sometimes it shouts. And sometimes a film arrives as a gentle nudge—a story that opens your heart, shifts your perspective, and leaves a quiet knowing.',
      'Watching movies can be a sacred pause: a warm hug on a cold evening, a cozy blanket for the soul. These favorites carry hope, empathy, and spiritual insight.',
      'Anand: “Zindagi badi honi chahiye, lambi nahi.” The film follows Anand, who is terminally ill yet teaches everyone around him to live fully with joy and positivity, showing that depth matters more than length.',
      'PK (2014): An alien questions blind faith and religious dogma, inviting us to think rationally and avoid following rituals without reflection.',
      'Taare Zameen Par: A tender reminder about childhood trauma and learning differences, urging empathy and understanding for children who see the world differently.',
      'Tamasha: A call to embrace your true self and break free from expectations that dim your authentic story.',
      'Talaash (2012): A meditation on grief and the unseen realms, encouraging acceptance of loss and the courage to find closure.',
      'Dear Zindagi (2016): An ode to mental health and embracing life’s imperfections; it normalizes seeking help and learning new ways to care for yourself.',
      'These films invite reflection: What beliefs need softening? Where can you choose compassion over judgment? Which story helps you see your own life with kinder eyes?',
      'What movie would you add to this list, and which one feels like a warm hug to you?',
    ],
  },
  {
    id: 'fallback-self-toxicity',
    title: '7 Subtle Ways You Might Be Toxic to Yourself (And How I Learned to Stop)',
    slug: '7-subtle-ways-you-might-be-toxic-to-yourself',
    category: 'Self Growth',
    image_url: '/images/sound-bathing.jpg',
    excerpt:
      'Self-toxicity is quiet but draining: doubt, overhelping, comparison, and fear disguised as perfectionism. Here are seven habits I had—and how I’m unlearning them.',
    created_at: '2024-12-26T00:00:00.000Z',
    published: true,
    content: [
      'Self-toxicity can look normal: helping everyone else, scrolling and feeling behind, overthinking what could go wrong, doubting your own wins. It quietly drains energy, joy, and confidence.',
      'Here are seven subtle ways I was toxic to myself—and what helped me stop:',
      '1) Constantly doubting yourself: I finished big projects and gave myself zero credit, nitpicking tiny flaws. Fix: celebrate wins—small and big—to reinforce self-trust.',
      '2) Hesitating to ask for help: I treated asking as weakness and carried everything alone until I was empty. Fix: asking for help is strength; let others share the load.',
      '3) Comparing your life to others: Instagram highlights made me feel behind. Fix: honor your own timeline and progress; appreciate your unique story.',
      '4) Putting everyone else first: I skipped meals and rest to help others, glorifying sacrifice. Fix: self-care is not selfish; you cannot pour from an empty cup.',
      '5) Avoiding conflict at all costs: I bit my tongue to “keep peace” and lost inner peace instead. Fix: speak your truth kindly—calm honesty protects both you and the relationship.',
      '6) Overcommitting to please others: “Sure, I can help!” left me exhausted and resentful. Fix: saying no is a powerful way to protect your energy.',
      '7) Procrastinating out of fear: perfectionism made me delay, overplan, and avoid mistakes. Fix: take imperfect action; progress follows courage, not avoidance.',
      'If any of these feel familiar, start with one small shift today: celebrate one win, ask for one bit of help, or say one honest no. Little acts of self-kindness add up to a healthier, kinder you.',
    ],
  },
  {
    id: 'fallback-unpopular-opinion-toxic',
    title: 'Unpopular Opinion: Maybe It Is Not “Toxic People,” It Is Toxic Ways',
    slug: 'unpopular-opinion-toxic-ways',
    category: 'Boundaries',
    image_url: '/images/manifestation-coaching.jpg',
    excerpt:
      'We rush to cut off “toxic people,” but often the work is healing our own toxic ways: boundaries, self-awareness, and choosing not to drink the poison.',
    created_at: '2024-12-28T00:00:00.000Z',
    published: true,
    content: [
      'Unpopular opinion: people can be toxic—and so can our ways of relating. The rise of the word “toxic” has made cutting people off feel like the default move.',
      'I remember the mix of relief and the gaping hole after cutting someone important from my life. Conflict subsided, but so did opportunities for growth.',
      'Society now champions “cut them off” as the ultimate boundary, so it is easy to assume any conflict means run. Sometimes, yes, stepping away is necessary to stay safe.',
      'And sometimes we are quick to label in others what we refuse to see in ourselves. The way we connect, let others’ opinions dominate, or let our own toxic traits spill out matters.',
      'Key: the best way to avoid toxic people is to stop engaging in toxic ways. Boundaries and self-responsibility change the dynamic.',
      'Childhood wires us to merge with caregivers; as adults we can separate our emotions, set healthy limits, and take responsibility for our well-being.',
      'While our past shapes us, we can learn conscious relating through self-awareness, communication, and personal growth. (This does not excuse staying with truly dangerous people.)',
      'We are invited to see the humanity in others just as we want ours to be seen. “Toxic people” stay toxic only if we keep drinking their poison.',
    ],
  },
]
