export const fallbackBlogs = [
  {
    id: 'fallback-17-second-rule',
    title: 'The 17-Second Rule: A Cheesecake Lesson at Delhi Airport',
    slug: '17-second-rule',
    category: 'Manifestation',
    image_url:
      'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=600&q=80',
    excerpt:
      '17 seconds of pure, joyful focus at a Delhi airport turned cheesecake disappointment into a fresh slice—here is the full story and how to practice the 17-second rule yourself.',
    created_at: '2024-12-15T00:00:00.000Z',
    published: true,
    content: [
      'Story — Cheesecake at Delhi airport',
      'Last July at Delhi airport, my son was craving a slice of cheesecake. Starbucks had just sold out, and disappointment hit fast.',
      'Instead of lingering there, I reminded him of the 17-second rule: hold a pure, positive thought for 17 seconds and you start activating its vibration. I was quietly hoping we might find a slice when we landed a couple of hours later.',
      'He closed his eyes, set a 17-second timer on his watch, and visualized a perfect slice—blueberry jelly on top, creamy filling, and a sweet graham crust. He felt the anticipation as if it were already in his hands.',
      'When he opened his eyes, he smiled and said it felt so real. We let it go, grabbed iced coffee, and found a corner table.',
      'Within minutes, the waiter returned: their outside baker had arrived early with a fresh batch of pastries—cheesecake included. The delight in my son’s eyes said everything.',
      'What is the 17-second rule?',
      'A concept popularized by Abraham Hicks: 17 seconds of undiluted focus sparks the vibration of your thought; 34, 51, and 68 seconds build momentum and make it feel closer and stronger.',
      'Science & spirit: your reticular activating system (RAS) highlights what you focus on, priming you to notice matching opportunities. Energetically, your field acts like a magnet, inviting aligned people and moments.',
      'How to practice — four quick steps',
      '1) Choose your thought: Pick one clear, uplifting idea (vision, desire, or feeling like joy/love/abundance).',
      '2) Focus for 17 seconds: Close your eyes, hold it with laser focus, feel it as if it is happening now.',
      '3) Build momentum: If it feels good, ride it to 34, 51, or 68 seconds—each checkpoint strengthens the signal.',
      '4) Release and receive: Let it go. Do not keep checking. Stay light and open to synchronicities.',
      'Start small: try it on a calm meeting, a smooth commute, or a helpful colleague. Notice how a short burst of focused attention can reset your energy and invite matching experiences.',
    ],
  },
  {
    id: 'fallback-cord-cutting-only-way',
    title: 'Is Cord Cutting the ONLY Way?',
    slug: 'is-cord-cutting-the-only-way',
    category: 'Energy Healing',
    image_url:
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80',
    excerpt:
      'Etheric cords link us to people, places, and lessons. Before you rush to “cut,” understand how cords behave, why lessons repeat, and how love + forgiveness can dissolve what hurts.',
    created_at: '2024-12-20T00:00:00.000Z',
    published: true,
    content: [
      'They say relationships are made in heaven, bound before birth. Yet breakups and broken friendships make us ask: where does that soul connection go when love turns to resentment?',
      'Let spirituality answer: we are linked by Etheric Cords—subtle energy structures connecting people, places, animals, and objects through our chakras. The quality of emotion running through these cords shapes how we relate physically, mentally, and emotionally.',
      'Etheric cords are not static. A bright, heart-centered bond can dim or shift as a relationship changes. Cords can link through heart, eye, and other chakras, moving with the dynamics of connection.',
      'Detachment and “cutting the cord” is often advised when breakups or heartaches bring discomfort. Cord cutting aims to release negative emotions, patterns, and influences, helping you reclaim energy and freedom.',
      'But is cord cutting the only way? Consider this story from a seeker who cut cords with her ex, felt instant relief, then found the relationship reignite—only to crash harder.',
      'Why be cautious with cord cutting? Energetic cords behave like roots—cutting can stimulate regrowth, sometimes stronger. The issues you hoped to dissolve may reactivate if the underlying lesson remains unlearned.',
      'Energy and vibration: everything carries a frequency. Relationships make us aware of these vibrations.',
      'Soul contracts and lessons: many spiritual traditions say souls agree to meet and grow together. Earth is a school.',
      'A gentler path: instead of cutting, consider cleansing and dissolving with awareness.',
      '1) Pause and observe: What lesson or pattern is repeating?',
      '2) Forgive and soften: Send forgiveness and compassion.',
      '3) Clear the field: Use breathwork, salt baths, or nature.',
      '4) Dialogue with the cord: Ask what it is teaching you.',
      '5) Seal and bless: Let the cord dissolve gently into light.',
    ],
  },
  {
    id: 'fallback-slow-down-reset',
    title: '10 Warning Signs Your Life Is Asking You to Slow Down and Reset',
    slug: '10-warning-signs-to-slow-down',
    category: 'Mindfulness',
    image_url:
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=600&q=80',
    excerpt:
      'Life whispers before it screams. Notice these 10 everyday signals—from clumsy mishaps to lost joy—that ask you to pause, realign, and reset.',
    created_at: '2024-12-22T00:00:00.000Z',
    published: true,
    content: [
      'Life has a way of whispering before it screams.',
      '1) A streak of clumsy accidents.',
      '2) A scattered mind.',
      '3) Irritation and anxiety.',
      '4) Frequent illnesses.',
      '5) Losing joy.',
      '6) Repeating angel numbers.',
      '7) Ignoring intuition.',
      '8) Clutter everywhere.',
      '9) Social autopilot.',
      '10) Sleep that does not restore.',
      'Bottom line: these signs are gentle nudges to pause.',
    ],
  },
  {
    id: 'fallback-movies-that-teach',
    title: 'Movies That Feel Like Warm Hugs for the Soul',
    slug: 'movies-that-feel-like-warm-hugs',
    category: 'Inspiration',
    image_url:
      'https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?auto=format&fit=crop&w=600&q=80',
    excerpt:
      'Films can be sacred pauses that whisper wisdom.',
    created_at: '2024-12-24T00:00:00.000Z',
    published: true,
    content: [
      'Sometimes life whispers its lessons.',
      'Anand',
      'PK',
      'Taare Zameen Par',
      'Tamasha',
      'Talaash',
      'Dear Zindagi',
    ],
  },
  {
    id: 'fallback-self-toxicity',
    title: '7 Subtle Ways You Might Be Toxic to Yourself',
    slug: '7-subtle-ways-you-might-be-toxic-to-yourself',
    category: 'Self Growth',
    image_url:
      'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=600&q=80',
    excerpt:
      'Self-toxicity is quiet but draining.',
    created_at: '2024-12-26T00:00:00.000Z',
    published: true,
    content: [
      'Constant self-doubt.',
      'Fear of asking for help.',
      'Comparison.',
      'Over-giving.',
      'Conflict avoidance.',
      'Overcommitting.',
      'Procrastination.',
    ],
  },
  {
    id: 'fallback-unpopular-opinion-toxic',
    title: 'Unpopular Opinion: Maybe It Is Not “Toxic People,” It Is Toxic Ways',
    slug: 'unpopular-opinion-toxic-ways',
    category: 'Boundaries',
    image_url:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    excerpt:
      'We rush to cut off toxic people.',
    created_at: '2024-12-28T00:00:00.000Z',
    published: true,
    content: [
      'Unpopular opinion.',
      'Cutting off is not always healing.',
      'Boundaries matter.',
      'Self-awareness shifts dynamics.',
      'Healing your ways first.',
    ],
  },
]
